trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: Maven@4
    displayName: Build and test with Maven
    inputs:
      mavenPomFile: pom.xml
      goals: clean install
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: JDKVersion
      jdkVersionOption: '1.17'
      mavenVersionOption: Default
